# Generated by Django 5.0.6 on 2025-02-21 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_application_resume'),
        ('accounts', '0002_auto_YYYYMMDD_HHMM'),
    ]

    operations = [
    ]
