# Generated by Django 5.0.6 on 2025-02-22 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_merge_20250221_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='email',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='password',
        ),
        migrations.RemoveField(
            model_name='hr',
            name='email',
        ),
        migrations.RemoveField(
            model_name='hr',
            name='password',
        ),
        migrations.RemoveField(
            model_name='job',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='job_description',
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='ranking',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='application',
            name='resume_file',
            field=models.FileField(default='Default Organization', upload_to='resumes/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='first_name',
            field=models.CharField(default='default@example.com', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='last_name',
            field=models.CharField(default='Default First Name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hr',
            name='organization_email',
            field=models.EmailField(default='Default Last Name', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hr',
            name='organization_name',
            field=models.CharField(default='deafult_resume.pdf', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default='Default Location', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='description',
            field=models.TextField(default='Default Deescription'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.job'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('HR', 'HR'), ('Candidate', 'Candidate')], max_length=10),
        ),
    ]
