# Generated by Django 5.0.6 on 2025-02-22 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_application_resume_remove_candidate_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
