# Generated by Django 5.0.6 on 2025-02-22 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_application_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hr', to=settings.AUTH_USER_MODEL),
        ),
    ]
