# Generated by Django 5.0.6 on 2025-02-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_hr_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='resume_content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
