# Generated by Django 5.0.6 on 2025-02-23 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_resume_candidate_remove_resume_resume_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='job_id',
            field=models.IntegerField(default=1),
        ),
    ]
