# Generated by Django 5.0.6 on 2025-02-23 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_resume_job_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='job_id',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='resume_content',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='user_name',
        ),
        migrations.AddField(
            model_name='resume',
            name='candidate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.candidate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
